"""add post_upvotes table

Revision ID: 235700d9c9e2
Revises: f859c4d2a087
Create Date: 2026-01-19 11:59:22.517968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235700d9c9e2'
down_revision = 'f859c4d2a087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_upvotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_upvotes')
    # ### end Alembic commands ###
