"""Add upvotes to Post

Revision ID: 927cc083bdd3
Revises: df4243ffbb73
Create Date: 2025-12-04 09:55:08.078928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927cc083bdd3'
down_revision = 'df4243ffbb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('upvotes')

    # ### end Alembic commands ###
